[groups:elfin]
programs=wechat_elfin, wechat_access_token, actress_get_media_url, actress_store_media, actress_refresh_and_record, mongo, redis, twibot

[program:wechat_elfin]
command=/home/admin/.pyenv/versions/2.7.18/bin/python -B /home/admin/elfin/main.py
directory=/home/admin/elfin
user=admin
autorestart=true
redirect_stderr=true
stdout_logfile=/home/admin/elfin/log/supervisor.log
loglevel=info

[program:mongo]
command=/usr/bin/mongod --dbpath=/var/lib/mongodb --logpath=/home/admin/elfin/log/mongo.log 
directory=/home/admin/elfin
user=root
autorestart=false
redirect_stderr=true
stdout_logfile=/home/admin/elfin/log/supervisor.log
loglevel=info


# [program:wechat_access_token]
# command=python -B /home/admin/elfin/scripts/get_access_token.py
# directory=/home/admin/elfin
# user=www-data
# autorestart=true
# redirect_stderr=true
# stdout_logfile=/home/admin/elfin/log/supervisor.log
# loglevel=info
# 
# [program:actress_get_media_url]
# command=python -B /home/admin/actress/get_media_url.py
# directory=/home/admin/actress
# user=www-data
# autorestart=true
# redirect_stderr=true
# stdout_logfile=/home/admin/actress/get_media_url.log
# loglevel=info
# 
# 
# [program:actress_store_media]
# command=python -B /home/admin/actress/store_media.py
# directory=/home/admin/actress
# user=www-data
# autorestart=true
# redirect_stderr=true
# stdout_logfile=/home/admin/actress/store_media.log
# loglevel=info
# 
# 
# [program:actress_refresh_and_record]
# command=python -B /home/admin/actress/refresh_and_record.py
# directory=/home/admin/actress
# user=www-data
# autorestart=true
# redirect_stderr=true
# stdout_logfile=/home/admin/actress/request.log
# loglevel=info
# 
# 
# [program:twibot]
# command=python -B /home/admin/twibot/code.py
# directory=/home/admin/twibot
# user=www-data
# autorestart=true
# redirect_stderr=true
# stdout_logfile=/home/admin/twibot/log/supervisor.log
# loglevel=info
# 
# 
# [program:redis]
# command=/usr/bin/redis-server /etc/redis/redis.conf
# directory=/home/admin/elfin
# user=root
# autorestart=true
# redirect_stderr=true
# stdout_logfile=/home/admin/elfin/log/supervisor.log
# loglevel=info
