server {
    listen 80;
    server_name elfin.minganci.org;

    location /elfin/ {
        rewrite ^/elfin/(.*) /$1 break;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://127.0.0.1:9001;
    }

    ##
    # Logging Settings
    ##

    access_log /var/log/nginx/access.log;
}
